### ISSUE TITLE
Allow to run multiple l3roamd instances

### ISSUE THREAD

**Issue by ohrensessel** [freifunk-gluon/l3roamd#36]
For a setup where we run multiple freifunk mesh domains on a single gateway it would be helpful if l3roamd could be run multiple times on one machine. Currently this fails with `bind failed: Address already in use` as l3roamd binds to `:::5523` and not to the specific interfaces given as parameters.

Do you think there is a chance to get this into l3roamd?

**Comment by christf** [comment]
patches are always welcome :)

I think this should be easy to fix though. I may end up looking at it procrastinating other l3roamd issues... :)

**Comment by ohrensessel** [comment]
I would be very grateful if you would do so. I'm not at all familiar with l3roamd code and probably will have a hard time getting this to work.

**Comment by christf** [comment]
this should be possible now.
