### ISSUE TITLE
no license specified

### ISSUE THREAD

**Issue by rotanid** [freifunk-gluon/l3roamd#45]
this package is missing a license specification.
please chose one and get approval from every other author that contributed to this software.

**Comment by penguineer** [comment]
Is there any reason not to use BSD or MIT license?

**Comment by penguineer** [comment]
@christf Can you please specify the new target license and note which contributors have not agreed yet?

**Comment by penguineer** [comment]
We assume the following license for all files lacking a specific annotation: https://opensource.org/licenses/BSD-2-Clause

**Comment by christf** [comment]
Some of the files explicitly were marked as 2 clause bsd license By Nils. Since he did not reply to my query  we can only assume that the whole project was meant to be released under this license.
For me this license is fine.

@t-8ch @oszilloskop @ctr49 @matwei do you agree with this?

**Comment by penguineer** [comment]
@T-X @mweinelt @rotanid Do you agree?

**Comment by t-8ch** [comment]
@christf Anything accepted by OSI or Debian is fine with me.

**Comment by rotanid** [comment]
i'm not a contributor to this code so my vote doesn't matter.

**Comment by mweinelt** [comment]
> i'm not a contributor to this code so my vote doesn't matter.

Same.

**Comment by matwei** [comment]
> Some of the files explicitly were marked as 2 clause bsd license By Nils. Since he did not reply to my query we can only assume that the whole project was meant to be released under this license.
> For me this license is fine.
> 
> @t-8ch @oszilloskop @ctr49 @matwei do you agree with this?

For me this license is fine too.

**Comment by ctr49** [comment]
I agree for my part of the contribution, but I'm not sure if it's safe to assume that the license used in 2 files can be applied for other contributions.

**Comment by penguineer** [comment]
> I'm not sure if it's safe to assume that the license used in 2 files can be applied for other contributions.

We could argue as follows:
1) The original author has created this project in an open-source environment.
2) Some of the files contain a specific license, while the rest of the files do not contain any license notice at all.

This we can assume that the author had the intention for this project to be open source under the 2-clause BSD license.

**Comment by lost-tty** [comment]
Any license is fine for my contributions. Consider it public domain or whatever makes most sense for this project to be useful for as many people as possible.

**Comment by oszilloskop** [comment]
Any license is fine for my little documentation contribution.

**Comment by penguineer** [comment]
Based on this discussion I will go with the 2-clause BSD license and consider this issue closed.
