### ISSUE TITLE
vector implementation - allow to insert in a sorted way

### ISSUE THREAD

**Issue by christf** [freifunk-gluon/l3roamd#49]
that means we could access elements of the vector faster.

**Comment by penguineer** [comment]
This would be a heap instead of a vector. Maybe we are using the wrong structure?

**Comment by penguineer** [comment]
https://github.com/freifunk-gluon/l3roamd/blob/master/src/vector.c#L50

This function could be much more efficient if the allocated size is strictly controlled and we can assume that alloc sizes are always a power of 2.

**Comment by penguineer** [comment]
https://github.com/freifunk-gluon/l3roamd/blob/master/src/vector.c#L74

I propose adding an append function - no need to copy unused memory.

**Comment by christf** [comment]
well, the common use case will be a few (dozen?) local clients. There was no performance analysis yet however it is doubtful we will see bottlenecks in the near future. Let's see that we have a problem and then we understand it and implement improvements.
