### ISSUE TITLE
Feature: learn new clients on bridge-interfaces

### ISSUE THREAD

**Issue by christf** [freifunk-gluon/l3roamd#5]
https://github.com/tcatm/l3roamd/issues/24

For wifi clients the nl80211 can inform us about new clients. This may also be possible for bridges.

Relevant kernel code:

    RTM_NEWNEIGH
    http://lxr.free-electrons.com/source/net/bridge/br_fdb.c#L547
    http://lxr.free-electrons.com/source/net/bridge/br_fdb.c#L682

**Comment by matwei** [comment]
You mean when the client interface (option -i) is an ethernet bridge?

**Comment by christf** [comment]
On Fri, May 05, 2017 at 07:17:32AM -0700, Mathias Weidner wrote:
>You mean when the client interface (option -i) is an ethernet bridge?
Exactly.

-- 
()  ascii ribbon campaign - against html e-mail
/\  against proprietary attachments

**Comment by christf** [comment]
it also would be interesting if this works on regular interfaces and veth.

**Comment by christf** [comment]
this might also be possible using [BPF](https://biot.com/capstats/bpf.html)

**Comment by christf** [comment]
this is now possible. closing.
