### ISSUE TITLE
add example for running l3roamd

### ISSUE THREAD

**Issue by PolynomialDivision** [freifunk-gluon/l3roamd#69]
Could someone provide some example configuration of l3roamd?
I have a babel test network, but not sure how to use l3roamd correctly.

**Comment by christf** [comment]
On Sat, Aug 15, 2020 at 12:20:44AM -0700, Polynomdivision wrote:
>Could someone provide some example configuration of l3roamd?
>I have a babel test network, but not sure how to use l3roamd correctly.

You need to run l3roamd on every node running babel on your network.
the gluon package provides a usage example:
https://github.com/freifunk-gluon/gluon/blob/master/package/gluon-l3roamd/files/etc/init.d/gluon-l3roamd#L55


-- 
()  ascii ribbon campaign - against html e-mail
/\  www.asciiribbon.org   - against proprietary attachments

**Comment by PolynomialDivision** [comment]
Thanks!

**Comment by PolynomialDivision** [comment]
Sry, I saw that Frankfurt was(?) already running some gluon firmware with that layer 3 capabilities.
In the wiki everything points to nilsschneider.net and this site is down. Even in the experimental version this is not activated, or?

Freifunk Bremen had one version in its archive: https://github.com/FreifunkBremen/gluon-site-ffhb/tree/breminale2019-babel

**Comment by PolynomialDivision** [comment]
Can u just say how u test this in the developing phase?
Do u use gluon, or do a manual setup with babeld and l3roamd? :)

**Comment by christf** [comment]
On Tue, Aug 18, 2020 at 04:33:34AM -0700, Polynomdivision wrote:
>Sry, I saw that Frankfurt was(?) already running some gluon firmware with that layer 3 capabilities.
>In the wiki everything points to nilsschneider.net and this site is down. Even in the experimental version this is not activated, or?
This was running in Frankfurt but development in that community ceased.

Magdeburg is now running their upcoming net with babel and l3roamd - see 
FreifunkMD.

Cheers

Christof


-- 
()  ascii ribbon campaign - against html e-mail
/\  www.asciiribbon.org   - against proprietary attachments

**Comment by christf** [comment]
On Tue, Aug 18, 2020 at 04:39:12AM -0700, Polynomdivision wrote:
>Can u just say how u test this in the developing phase?
>Do u use gluon, or do a manual setup with babeld and l3roamd? :)
Sure. I use gluon and multiple ff-nodes. Usually I compile images from a 
local branch to do this as this helps me avoid dropping patches.

In early stages I did manual configuration on the node to try things out 
but since we have a fairly stable setup now development happens with 
experimental firmware builds using autoupdater.



-- 
()  ascii ribbon campaign - against html e-mail
/\  www.asciiribbon.org   - against proprietary attachments

**Comment by PolynomialDivision** [comment]
> Magdeburg is now running their upcoming net with babel and l3roamd - see

Thanks. Just try the experimental build but something does not work with gw connection. But local network works! :)
You are missing `socat` in your builds(?). ;)

**Comment by PolynomialDivision** [comment]
I just played around with a setup consisting of the Magdeburg-Firmware with two nodes. Is it correct how that behaved?

I tried to push the client around and provoke roaming by varying the signal strength of the APs or banning the clients with hostapd-del-cmd.

Both routers had the same IPv4 address. The IPv6 addresses were different. This means the client keeps the same IPv4 gateway after it has roamed.

I was a bit surprised that with `echo get_clients | socat - /var/run/l3roamd.sock` I only see the clients that are locally connected to one router. I kind of thought I would see all of them, since the table is called distributed database. Anyway the roaming worked, sometimes my IPv4 address changed, but I think not always. But there was definitely a disconnect in the connectivity. I need to see if the TCP connections are holding up.

It was always like this with a connect INACTIVE -> ACTIVE. And after a disconnect ACTIVE -> INACTIVE.

Are the assumptions wrong?
- The IPv4 address should remain the same
- The IPv6 address should remain the same
- No Teardown of TCP connections

I will go on with testing. Maybe I did some mistake. Thanks for your awesome tool. :)
