### ISSUE TITLE
repeat claim up to 3 times

### ISSUE THREAD

**Issue by christf** [freifunk-gluon/l3roamd#7]
see: https://github.com/tcatm/l3roamd/issues/14

In case of no response a claim should be tried up to three times, each after a short delay of about 1s if no response is received. Use the relinquished flag to determine when to stop.

**Comment by christf** [comment]
if there is no response, the client may be new.

**Comment by christf** [comment]
@t-8ch what do you think, is this worth re-introducing a taskqueue and a scheduler?
I ripped that one out previously to make l3roamd netlink-event-driven but it seems we still want to be able to schedule actions in the future....
ideas?

**Comment by t-8ch** [comment]
I don't see a way of having for example the kernel do the scheduling for us directly.
(I hoped we could use a reliable transport protocol, but that does not work in the multicast case).
Maybe we can reintroduce the previous scheduler?

**Comment by christf** [comment]
it is back now. Now it needs to be implemented after considering data structures. We do not want claims to happen 3 times, we want claims to happen up to 3 times. Since they are answered with an info packet, we can stop sending claims once we received an info packet for a claim.
At the same time, if a client is new, no info packet may be sent/received at all, so we need to stop repeating after a while.

**Comment by christf** [comment]
this is addressed by #30 
Closing this issue as one ticket is enough to track this.
